# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="/usr/share/ohmyzsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="random"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 7

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	alias-finder
	colorize
	copybuffer
	copyfile
	copypath
	dirhistory
	docker
	docker-compose
	encode64
	extract
	fzf
	git
	git-extras
	gitignore
	history
	jsontools
	man
	# nmap
	# node
	# npm
	# nvm
	pip
	python
	sudo
	# supervisor
	systemd
	# ufw
	z
	zsh-autosuggestions
	zsh-completions
	zsh-syntax-highlighting
)
# Plugin Notes:

# alias-finder plugin
zstyle ':omz:plugins:alias-finder' autoload yes # disabled by default
zstyle ':omz:plugins:alias-finder' longer yes # disabled by default
zstyle ':omz:plugins:alias-finder' exact yes # disabled by default
zstyle ':omz:plugins:alias-finder' cheaper yes # disabled by default
# They gets auto suggested

# colorize plugin
# need chroma or pygmentize installed and pygmentize is default
# Usage: ccat <file> [files] / cless [less-options] <file> [files] (LESSOPEN and LESSCLOSE)

# copybuffer plugin
# Usage: ctrl o (copy's current command into clicpboard)

# copyfile plugin
# Usage: copyfile <file> (copy the file content to clipboard)

# copypath plugin
# Usage: copypath <file/directory> (copy the current file/directory's  absolute path to the clipboard)

# dirhistory plugin
# Usage: alt left/right/up/down (previous, next, parent, child directory Respectively)

# encode64 plugin
# Usage: encode64/decode64/encodefile64 (aliases e64/d64/ef64) <data>/<data>/<file>

# extract plugin
# Usage: extract <file> (a wide vairty of file format is supported)

# fzf plugin
# need fzf installated
# apt install fzf
# Usage: key bindings (CTRL-T, CTRL-R, ALT-C):

# gitignore plugin
# Usage: gi list, gi [TemplateName]

# jsontools plugin
# Usage: pp_json/is_json/urlencode_json/urldecode_json (pipe into them todo them respectively)

# man plugin
# Usage: Esc + man (add man before the previous command)

# sudo plugin
# Usage: Esc Twice (to put sudo in current/previous command)

# z plugin
# z -h (for help)
# Usage: z <directory regex> (any substring will work)	
# Example:
# /usr/bin$ z plug  # Even 'z p' might suffice
# ~/.oh-my-zsh/plugins$

# zsh-plugins
# need to manually add them in the custom plugin folder
# git clone https://github.com/zsh-users/zsh-autosuggestions.git ${ZSH_CUSTOM}/plugins/zsh-autosuggestions
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting
# git clone https://github.com/zsh-users/zsh-completions.git ${ZSH_CUSTOM}/plugins/zsh-completions

# many of the plugins are for aliases, so use alias and find and get used to the aliases for faster execution 

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zs='nano /etc/zsh/zshrc'
alias cls='clear'
